"""add invoices table for GST and TDS compliance

Revision ID: 023dc7042592
Revises: a943ae816b1e
Create Date: 2026-10-06 11:36:13.882872
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '023dc7042592'
down_revision: Union[str, None] = 'a943ae816b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
