import pgvector
"""add skill_embedding vector column to doctor

Revision ID: 1c3074935b4f
Revises: 22a7d1e490bd
Create Date: 2026-10-06 08:17:42.079962
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1c3074935b4f'
down_revision: Union[str, None] = '22a7d1e490bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('skill_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'skill_embedding')
    # ### end Alembic commands ###
