"""add gps attendance fields to shift

Revision ID: 22a7d1e490bd
Revises: ad11a7546dd9
Create Date: 2026-10-06 08:08:05.772118
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '22a7d1e490bd'
down_revision: Union[str, None] = 'ad11a7546dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('check_in_time', sa.DateTime(), nullable=True))
    op.add_column('shifts', sa.Column('check_out_time', sa.DateTime(), nullable=True))
    op.add_column('shifts', sa.Column('check_in_lat', sa.Float(), nullable=True))
    op.add_column('shifts', sa.Column('check_in_lon', sa.Float(), nullable=True))
    op.add_column('shifts', sa.Column('check_out_lat', sa.Float(), nullable=True))
    op.add_column('shifts', sa.Column('check_out_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'check_out_lon')
    op.drop_column('shifts', 'check_out_lat')
    op.drop_column('shifts', 'check_in_lon')
    op.drop_column('shifts', 'check_in_lat')
    op.drop_column('shifts', 'check_out_time')
    op.drop_column('shifts', 'check_in_time')
    # ### end Alembic commands ###
