"""Initial ABDM schema: users, hpr_profiles, facilities, shifts

Revision ID: 25e704c37a55
Revises: 
Create Date: 2026-10-05 08:24:33.217259
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25e704c37a55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_area', sa.String(), nullable=False),
    sa.Column('transit_corridor', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('abdm_facility_id', sa.String(), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abdm_facility_id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_location_area'), 'facilities', ['location_area'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('hpr_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hpr_id', sa.String(), nullable=True),
    sa.Column('hpr_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.String(), nullable=True),
    sa.Column('is_council_verified', sa.String(), nullable=True),
    sa.Column('is_work_verified', sa.String(), nullable=True),
    sa.Column('application_status', sa.String(), nullable=True),
    sa.Column('council_name', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('qualification_details', sa.JSON(), nullable=True),
    sa.Column('work_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_hpr_profiles_hpr_id'), 'hpr_profiles', ['hpr_id'], unique=True)
    op.create_index(op.f('ix_hpr_profiles_id'), 'hpr_profiles', ['id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('role_required', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('date_raw', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('offered_rate_inr', sa.Integer(), nullable=False),
    sa.Column('rate_basis', sa.String(), nullable=False),
    sa.Column('urgency_level', sa.Enum('CRITICAL', 'HIGH', 'ROUTINE', name='urgencylevel'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'COMPLETED', 'CANCELLED', name='shiftstatus'), nullable=True),
    sa.Column('requires_mmc', sa.Boolean(), nullable=True),
    sa.Column('requires_mnc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_hpr_profiles_id'), table_name='hpr_profiles')
    op.drop_index(op.f('ix_hpr_profiles_hpr_id'), table_name='hpr_profiles')
    op.drop_table('hpr_profiles')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_location_area'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
