"""add_doctors_and_financial_tracking

Revision ID: 3b416f6dd012
Revises: 3f6024d2c64d
Create Date: 2026-09-30 13:43:36.208068
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b416f6dd012'
down_revision: Union[str, None] = '3f6024d2c64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('nmc_registration', sa.String(), nullable=True),
    sa.Column('base_location', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('preferred_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_rate', sa.Numeric(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('availability_calendar', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.add_column('shift_requests', sa.Column('assigned_doctor_id', sa.UUID(), nullable=True))
    op.add_column('shift_requests', sa.Column('assigned_doctor_name', sa.String(), nullable=True))
    op.add_column('shift_requests', sa.Column('clinic_charge', sa.Numeric(), nullable=True))
    op.add_column('shift_requests', sa.Column('doctor_payout', sa.Numeric(), nullable=True))
    op.add_column('shift_requests', sa.Column('platform_margin', sa.Numeric(), nullable=True))
    op.add_column('shift_requests', sa.Column('would_use_again', sa.Boolean(), nullable=True))
    op.add_column('shift_requests', sa.Column('would_pay_platform_fee', sa.Boolean(), nullable=True))
    op.add_column('shift_requests', sa.Column('max_acceptable_fee', sa.Numeric(), nullable=True))
    op.add_column('shift_requests', sa.Column('feedback_notes', sa.Text(), nullable=True))
    op.drop_column('shift_requests', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_requests', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('shift_requests', 'feedback_notes')
    op.drop_column('shift_requests', 'max_acceptable_fee')
    op.drop_column('shift_requests', 'would_pay_platform_fee')
    op.drop_column('shift_requests', 'would_use_again')
    op.drop_column('shift_requests', 'platform_margin')
    op.drop_column('shift_requests', 'doctor_payout')
    op.drop_column('shift_requests', 'clinic_charge')
    op.drop_column('shift_requests', 'assigned_doctor_name')
    op.drop_column('shift_requests', 'assigned_doctor_id')
    op.drop_table('doctors')
    # ### end Alembic commands ###
