"""create_shift_requests_table

Revision ID: 3f6024d2c64d
Revises: 
Create Date: 2026-09-30 09:30:15.884343
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3f6024d2c64d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('clinic_pincode', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('shift_date', sa.String(), nullable=False),
    sa.Column('shift_time', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHING', 'DOCTOR_NOTIFIED', 'ACCEPTED', 'COMPLETED', 'CANCELLED', 'FAILED', name='shiftstatus'), nullable=False),
    sa.Column('reason_posted', sa.String(), nullable=True),
    sa.Column('current_sourcing_method', sa.String(), nullable=True),
    sa.Column('doctors_contacted_count', sa.Integer(), nullable=True),
    sa.Column('time_to_fill_minutes', sa.Integer(), nullable=True),
    sa.Column('clinic_satisfaction', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_requests')
    # ### end Alembic commands ###
