"""add doctor master record, credentials, documents, and verification events

Revision ID: 72324dd267e1
Revises: e4928050d436
Create Date: 2026-10-06 06:50:06.721764
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '72324dd267e1'
down_revision: Union[str, None] = 'e4928050d436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'VERIFIED', 'SHIFT_READY', 'SUSPENDED', 'EXPIRED', 'REJECTED', name='doctorstatus'), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_authority', sa.String(length=200), nullable=True),
    sa.Column('registration_status', sa.String(length=50), nullable=True),
    sa.Column('registration_expiry', sa.DateTime(), nullable=True),
    sa.Column('mbbs_university', sa.String(length=200), nullable=True),
    sa.Column('mbbs_year', sa.Integer(), nullable=True),
    sa.Column('pg_degree', sa.String(length=50), nullable=True),
    sa.Column('pg_specialty', sa.String(length=100), nullable=True),
    sa.Column('pg_institution', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_shifts', sa.JSON(), nullable=True),
    sa.Column('availability_notes', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_holder_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_doctor_code'), 'doctors', ['doctor_code'], unique=True)
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_phone'), 'doctors', ['phone'], unique=True)
    op.create_index(op.f('ix_doctors_registration_number'), 'doctors', ['registration_number'], unique=False)
    op.create_index(op.f('ix_doctors_status'), 'doctors', ['status'], unique=False)
    op.create_table('doctor_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('credential_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_credentials_doctor_id'), 'doctor_credentials', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_credentials_id'), 'doctor_credentials', ['id'], unique=False)
    op.create_table('doctor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('IDENTITY_AADHAAR', 'IDENTITY_PAN', 'IDENTITY_PASSPORT', 'IDENTITY_DRIVING_LICENSE', 'REGISTRATION_CERTIFICATE', 'MBBS_CERTIFICATE', 'PG_CERTIFICATE', 'EXPERIENCE_CERTIFICATE', 'SPECIALIZATION_CERTIFICATE', 'PROFILE_PHOTO', 'SELFIE', 'DECLARATION', 'BANK_DETAILS', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_documents_doctor_id'), 'doctor_documents', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_documents_id'), 'doctor_documents', ['id'], unique=False)
    op.create_table('verification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('verification_type', sa.Enum('IDENTITY', 'NAME_MATCH', 'PHOTO_MATCH', 'REGISTRATION_NUMBER', 'REGISTRATION_AUTHORITY', 'REGISTRATION_STATUS', 'DATE_CHECKED', 'MBBS_CERTIFICATE', 'PG_QUALIFICATION', 'SPECIALIZATION', 'EXPERIENCE', 'BANK_DETAILS', 'DECLARATION', 'ONBOARDING', name='verificationtype'), nullable=False),
    sa.Column('result', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW', name='verificationresult'), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('old_status', sa.Enum('REGISTERED', 'VERIFIED', 'SHIFT_READY', 'SUSPENDED', 'EXPIRED', 'REJECTED', name='doctorstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('REGISTERED', 'VERIFIED', 'SHIFT_READY', 'SUSPENDED', 'EXPIRED', 'REJECTED', name='doctorstatus'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_events_doctor_id'), 'verification_events', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_verification_events_id'), 'verification_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_events_id'), table_name='verification_events')
    op.drop_index(op.f('ix_verification_events_doctor_id'), table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index(op.f('ix_doctor_documents_id'), table_name='doctor_documents')
    op.drop_index(op.f('ix_doctor_documents_doctor_id'), table_name='doctor_documents')
    op.drop_table('doctor_documents')
    op.drop_index(op.f('ix_doctor_credentials_id'), table_name='doctor_credentials')
    op.drop_index(op.f('ix_doctor_credentials_doctor_id'), table_name='doctor_credentials')
    op.drop_table('doctor_credentials')
    op.drop_index(op.f('ix_doctors_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_registration_number'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_phone'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_code'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
