"""add title column to shift model

Revision ID: 7d4a921df778
Revises: cfb0d5eb19dd
Create Date: 2026-10-06 07:59:33.419999
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7d4a921df778'
down_revision: Union[str, None] = 'cfb0d5eb19dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'title')
    # ### end Alembic commands ###
