"""add disputes table for refund and no-show workflows

Revision ID: 7e3287f6180c
Revises: 023dc7042592
Create Date: 2026-10-06 11:44:23.090941
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7e3287f6180c'
down_revision: Union[str, None] = '023dc7042592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('dispute_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('amount_claimed', sa.Float(), nullable=True),
    sa.Column('amount_refunded', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_doctor_id'), 'disputes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_disputes_hospital_id'), 'disputes', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_index(op.f('ix_disputes_shift_id'), 'disputes', ['shift_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_shift_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_hospital_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_doctor_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
