"""rename metadata to extra_data to avoid sqlalchemy conflict

Revision ID: 8a67194b8da8
Revises: 72324dd267e1
Create Date: 2026-10-06 07:22:53.848304
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8a67194b8da8'
down_revision: Union[str, None] = '72324dd267e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_credentials', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_column('doctor_credentials', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_credentials', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('doctor_credentials', 'extra_data')
    # ### end Alembic commands ###
