"""add missing doctor trust behavior columns

Revision ID: 8e5e6945861d
Revises: bc0c26001d91
Create Date: 2026-10-06 11:54:07.926840
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8e5e6945861d'
down_revision: Union[str, None] = 'bc0c26001d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('completed_shift_count', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('no_show_count', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('late_check_in_count', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('last_trust_calculated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'last_trust_calculated_at')
    op.drop_column('doctors', 'late_check_in_count')
    op.drop_column('doctors', 'no_show_count')
    op.drop_column('doctors', 'completed_shift_count')
    # ### end Alembic commands ###
