"""add latitude longitude to facilities

Revision ID: aa95aedbdbb1
Revises: 25e704c37a55
Create Date: 2026-10-05 13:01:15.376074
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'aa95aedbdbb1'
down_revision: Union[str, None] = '25e704c37a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
