"""add required_specialty to shift model

Revision ID: acbbbc7c9364
Revises: 7d4a921df778
Create Date: 2026-10-06 08:02:16.498371
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'acbbbc7c9364'
down_revision: Union[str, None] = '7d4a921df778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('required_specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'required_specialty')
    # ### end Alembic commands ###
