"""add assigned_doctor_id to shift

Revision ID: ad11a7546dd9
Revises: acbbbc7c9364
Create Date: 2026-10-06 08:04:19.906168
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ad11a7546dd9'
down_revision: Union[str, None] = 'acbbbc7c9364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'assigned_doctor_id')
    # ### end Alembic commands ###
