"""add ledger_entries and shift escrow fields

Revision ID: bbdf593281c7
Revises: 1c3074935b4f
Create Date: 2026-10-06 11:23:40.822897
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bbdf593281c7'
down_revision: Union[str, None] = '1c3074935b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('razorpay_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.add_column('shifts', sa.Column('escrow_status', sa.String(), nullable=True))
    op.add_column('shifts', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'razorpay_payment_id')
    op.drop_column('shifts', 'escrow_status')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
