"""add trust snapshots and doctor trust fields

Revision ID: bc0c26001d91
Revises: 7e3287f6180c
Create Date: 2026-10-06 11:48:04.594042
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bc0c26001d91'
down_revision: Union[str, None] = '7e3287f6180c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trust_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('completed_shifts', sa.Integer(), nullable=False),
    sa.Column('no_shows', sa.Integer(), nullable=False),
    sa.Column('late_check_ins', sa.Integer(), nullable=False),
    sa.Column('open_disputes', sa.Integer(), nullable=False),
    sa.Column('refunded_disputes', sa.Integer(), nullable=False),
    sa.Column('verification_approved', sa.Integer(), nullable=False),
    sa.Column('verification_rejected', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_snapshots_calculated_at'), 'trust_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_trust_snapshots_doctor_id'), 'trust_snapshots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_trust_snapshots_id'), 'trust_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_trust_snapshots_score'), 'trust_snapshots', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_snapshots_score'), table_name='trust_snapshots')
    op.drop_index(op.f('ix_trust_snapshots_id'), table_name='trust_snapshots')
    op.drop_index(op.f('ix_trust_snapshots_doctor_id'), table_name='trust_snapshots')
    op.drop_index(op.f('ix_trust_snapshots_calculated_at'), table_name='trust_snapshots')
    op.drop_table('trust_snapshots')
    # ### end Alembic commands ###
