"""add required_specialty to shift and home_transit_corridor to doctor for matching

Revision ID: cfb0d5eb19dd
Revises: fa135f35d68c
Create Date: 2026-10-06 07:54:20.456989
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfb0d5eb19dd'
down_revision: Union[str, None] = 'fa135f35d68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('home_transit_corridor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'home_transit_corridor')
    # ### end Alembic commands ###
