"""add hospital_admins table for web portal

Revision ID: e4928050d436
Revises: aa95aedbdbb1
Create Date: 2026-10-05 14:09:09.144123
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e4928050d436'
down_revision: Union[str, None] = 'aa95aedbdbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_admins_email'), 'hospital_admins', ['email'], unique=True)
    op.create_index(op.f('ix_hospital_admins_id'), 'hospital_admins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_admins_id'), table_name='hospital_admins')
    op.drop_index(op.f('ix_hospital_admins_email'), table_name='hospital_admins')
    op.drop_table('hospital_admins')
    # ### end Alembic commands ###
