"""add hospital verification fields to facility

Revision ID: fa135f35d68c
Revises: 8a67194b8da8
Create Date: 2026-10-06 07:30:44.962210
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa135f35d68c'
down_revision: Union[str, None] = '8a67194b8da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('address', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('city', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('state', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('pin_code', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('landline', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('mobile', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('email', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('website', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('facilities', sa.Column('authorized_contact_name', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('authorized_contact_phone', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('facilities', sa.Column('verified_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_facilities_is_verified'), 'facilities', ['is_verified'], unique=False)
    op.create_index(op.f('ix_facilities_pin_code'), 'facilities', ['pin_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_pin_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_is_verified'), table_name='facilities')
    op.drop_column('facilities', 'verified_at')
    op.drop_column('facilities', 'gst_number')
    op.drop_column('facilities', 'authorized_contact_phone')
    op.drop_column('facilities', 'authorized_contact_name')
    op.drop_column('facilities', 'is_verified')
    op.drop_column('facilities', 'website')
    op.drop_column('facilities', 'email')
    op.drop_column('facilities', 'mobile')
    op.drop_column('facilities', 'landline')
    op.drop_column('facilities', 'pin_code')
    op.drop_column('facilities', 'state')
    op.drop_column('facilities', 'city')
    op.drop_column('facilities', 'address')
    # ### end Alembic commands ###
